services:
  - type: web
    name: flag-quiz-java
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: production